# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "virtuo2"
client_id = "4b42f94a460e9681990ea4885692d455"
application_url = "https://enterprise-covers-higher-exactly.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_content"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://enterprise-covers-higher-exactly.trycloudflare.com/auth/callback",
  "https://enterprise-covers-higher-exactly.trycloudflare.com/auth/shopify/callback",
  "https://enterprise-covers-higher-exactly.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-04"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "vivify-textiles-demo-store.myshopify.com"
